# Generated by Django 4.2.7 on 2023-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=12)),
                ('grade7_center_number', models.IntegerField()),
                ('grade7_candidate_number', models.IntegerField()),
                ('candidate_name', models.CharField(max_length=200)),
                ('grade7_mathematics', models.IntegerField()),
                ('grade7_english', models.IntegerField()),
                ('grade7_shona', models.IntegerField()),
                ('grade7_social_science', models.IntegerField()),
                ('grade7_science_and_tech', models.IntegerField()),
                ('grade7_agriculture', models.IntegerField()),
                ('grade7_certificate', models.ImageField(upload_to='uploads/')),
                ('olevel_center_number', models.IntegerField()),
                ('olevel_candidate_number', models.IntegerField()),
                ('olevel_mathematics', models.IntegerField()),
                ('olevel_english', models.IntegerField()),
                ('olevel_shona', models.IntegerField()),
                ('olevel_history', models.IntegerField()),
                ('olevel_geography', models.IntegerField()),
                ('olevel_combined_science', models.IntegerField()),
                ('olevel_physics', models.IntegerField()),
                ('olevel_chemistry', models.IntegerField()),
                ('olevel_biology', models.IntegerField()),
                ('olevel_literature', models.IntegerField()),
                ('olevel_accounts', models.IntegerField()),
                ('olevel_commerce', models.IntegerField()),
                ('olevel_family_religious_studies', models.IntegerField()),
                ('olevel_arts', models.IntegerField()),
                ('olevel_computer_science', models.IntegerField()),
                ('olevel_woodwork', models.IntegerField()),
                ('olevel_metal_work', models.IntegerField()),
                ('olevel_technical_graphics', models.IntegerField()),
                ('olevel_building', models.IntegerField()),
                ('olevel_food_nutrition', models.IntegerField()),
                ('olevel_fashion_fabrics', models.IntegerField()),
                ('olevel_certificate', models.ImageField(upload_to='uploads/')),
                ('alevel_center_number', models.IntegerField()),
                ('alevel_candidate_number', models.IntegerField()),
                ('alevel_mathematics', models.IntegerField()),
                ('alevel_further_mathematics', models.IntegerField()),
                ('alevel_statistics', models.IntegerField()),
                ('alevel_accounts', models.IntegerField()),
                ('alevel_geography', models.IntegerField()),
                ('alevel_history', models.IntegerField()),
                ('alevel_chemistry', models.IntegerField()),
                ('alevel_biology', models.IntegerField()),
                ('alevel_literature', models.IntegerField()),
                ('alevel_economics', models.IntegerField()),
                ('alevel_bussiness_studies', models.IntegerField()),
                ('alevel_crop_science', models.IntegerField()),
                ('alevel_communication_skills', models.IntegerField()),
                ('alevel_certificate', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
