# Generated by Django 4.2.7 on 2023-11-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer_kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=12)),
                ('father_name', models.CharField(max_length=200)),
                ('father_surname', models.CharField(max_length=200)),
                ('father_birthplace', models.CharField(max_length=200)),
                ('father_id', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_surname', models.CharField(max_length=200)),
                ('mother_birthplace', models.CharField(max_length=200)),
                ('mother_id', models.CharField(max_length=200)),
                ('informant_mark', models.CharField(max_length=200)),
                ('informant_qualification', models.CharField(max_length=200)),
                ('informant_address', models.CharField(max_length=200)),
                ('date_registration', models.DateField()),
                ('birth_entry_no', models.CharField(max_length=10)),
                ('birth_certicate', models.ImageField(upload_to='uploads/')),
                ('first_name', models.CharField(max_length=200)),
                ('vilage_of_origin', models.CharField(max_length=200)),
                ('id_picture', models.ImageField(upload_to='uploads/')),
                ('type', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=3)),
                ('passport_no', models.CharField(max_length=9)),
                ('surname', models.CharField(max_length=200)),
                ('other_names', models.CharField(max_length=800)),
                ('nationality', models.CharField(max_length=200)),
                ('birth_place', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('date_of_issue', models.DateField()),
                ('country_of_permanent_residence', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('profession', models.CharField(max_length=200)),
                ('passport_picture', models.ImageField(upload_to='uploads/')),
                ('bride_name', models.CharField(max_length=200)),
                ('bride_surname', models.CharField(max_length=200)),
                ('groom_name', models.CharField(max_length=200)),
                ('groom_surname', models.CharField(max_length=200)),
                ('date_of_marriage', models.DateField()),
                ('place_of_marriage', models.CharField(max_length=200)),
                ('officiant_name', models.CharField(max_length=200)),
                ('officiant_surname', models.CharField(max_length=200)),
                ('witness1_name', models.CharField(max_length=200)),
                ('witness1_surname', models.CharField(max_length=200)),
                ('witness2_name', models.CharField(max_length=200)),
                ('witness2_surname', models.CharField(max_length=200)),
                ('unique_registration_Number', models.CharField(max_length=20)),
                ('marriage_certicate', models.ImageField(upload_to='uploads/')),
                ('date_of_death', models.DateField()),
                ('deceased_name', models.CharField(max_length=200)),
                ('deceased_surname', models.CharField(max_length=200)),
                ('sex', models.CharField(max_length=4)),
                ('age', models.IntegerField()),
                ('relationship_status', models.CharField(max_length=200)),
                ('death_cause', models.CharField(max_length=200)),
                ('residence', models.CharField(max_length=200)),
                ('occupation', models.CharField(max_length=200)),
                ('death_certicate', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
