# Generated by Django 4.2.7 on 2024-01-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crz', '0002_alter_customer_kyc_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_kyc',
            name='national_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
