from django.db import models

# Create your models here.
class customer_kyc(models.Model):
    national_id = models.CharField(max_length=12)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    surname = models.CharField(max_length=200, blank=True, null=True)
    birth_place = models.CharField(max_length=200, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    sex = models.CharField(max_length=1, blank=True, null=True)
    father_name = models.CharField(max_length=200, blank=True, null=True)
    father_surname = models.CharField(max_length=200, blank=True, null=True)
    father_birthplace = models.CharField(max_length=200, blank=True, null=True)
    father_id = models.CharField(max_length=200, blank=True, null=True)
    mother_name = models.CharField(max_length=200, blank=True, null=True)
    mother_surname = models.CharField(max_length=200, blank=True, null=True)
    mother_birthplace = models.CharField(max_length=200, blank=True, null=True)
    mother_id = models.CharField(max_length=200, blank=True, null=True)
    informant_mark = models.CharField(max_length=200, blank=True, null=True)
    informant_qualification = models.CharField(max_length=200, blank=True, null=True)
    informant_address = models.CharField(max_length=200, blank=True, null=True)
    date_registration = models.DateField(blank=True, null=True)
    birth_entry_no = models.CharField(max_length=10, blank=True, null=True)
    birth_certicate = models.ImageField(upload_to ='uploads/', blank=True, null=True)

    surname = models.CharField(max_length=200, blank=True, null=True)
    first_name = models.CharField(max_length=200, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    vilage_of_origin = models.CharField(max_length=200, blank=True, null=True)
    date_of_issue = models.DateField(blank=True, null=True)
    id_picture = models.ImageField(upload_to ='uploads/', blank=True, null=True)

    type = models.CharField(max_length=2, blank=True, null=True)
    state = models.CharField(max_length=3, blank=True, null=True)
    passport_no = models.CharField(max_length=9, blank=True, null=True)
    surname = models.CharField(max_length=200, blank=True, null=True)
    other_names = models.CharField(max_length=800, blank=True, null=True)
    nationality = models.CharField(max_length=200, blank=True, null=True)
    sex = models.CharField(max_length=1, blank=True, null=True)
    birth_place = models.CharField(max_length=200, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    date_of_issue = models.DateField(blank=True, null=True)
    country_of_permanent_residence = models.CharField(max_length=200, blank=True, null=True)
    expiry_date = models.DateField(blank=True, null=True)
    profession = models.CharField(max_length=200, blank=True, null=True)
    passport_picture = models.ImageField(upload_to ='uploads/', blank=True, null=True)

    bride_name = models.CharField(max_length=200, blank=True, null=True)
    bride_surname = models.CharField(max_length=200, blank=True, null=True)
    groom_name = models.CharField(max_length=200, blank=True, null=True)
    groom_surname = models.CharField(max_length=200, blank=True, null=True)
    date_of_marriage = models.DateField(blank=True, null=True)
    place_of_marriage = models.CharField(max_length=200, blank=True, null=True)
    officiant_name = models.CharField(max_length=200, blank=True, null=True)
    officiant_surname = models.CharField(max_length=200, blank=True, null=True)
    witness1_name = models.CharField(max_length=200, blank=True, null=True)
    witness1_surname = models.CharField(max_length=200, blank=True, null=True)
    witness2_name = models.CharField(max_length=200, blank=True, null=True)
    witness2_surname = models.CharField(max_length=200, blank=True, null=True)
    unique_registration_Number = models.CharField(max_length=20, blank=True, null=True)
    marriage_certicate = models.ImageField(upload_to ='uploads/', blank=True, null=True)

    date_of_death = models.DateField(blank=True, null=True)
    deceased_name = models.CharField(max_length=200, blank=True, null=True)
    deceased_surname = models.CharField(max_length=200, blank=True, null=True)
    sex = models.CharField(max_length=4, blank=True, null=True)
    age =  models.IntegerField(blank=True, null=True)
    relationship_status = models.CharField(max_length=200, blank=True, null=True)
    death_cause = models.CharField(max_length=200, blank=True, null=True)
    residence = models.CharField(max_length=200, blank=True, null=True)
    occupation = models.CharField(max_length=200, blank=True, null=True)
    death_certicate = models.ImageField(upload_to ='uploads/', blank=True, null=True)

    def __str__(self):
        return str(self.national_id)
    


